# Generated by Django 6.0.5 on 2026-06-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('sclass', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('picture', models.ImageField(upload_to='students_pics')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
