# Generated by Django 6.0.5 on 2026-06-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_studentmodel_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='sclass',
            new_name='studentclass',
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='picture',
            field=models.ImageField(upload_to='students_pics/'),
        ),
    ]
